### ISSUE TITLE
Exception FilesCouldBeMissed Eclipse Neon

### ISSUE THREAD

**Issue by KevinMoreau3** [jalios/eclipse-jcms-plugin-tools#11]
Version 2.0.3 Beta
Eclipse neon 2 

I have an recurring exception with Neon 2 with my plugins. 

> !ENTRY org.eclipse.core.jobs 4 2 2017-02-23 11:53:00.191
> !MESSAGE An internal error occurred during: "Check preview sync".
> !STACK 0
> java.lang.NullPointerException
> 	at com.jalios.ejpt.sync.strategy.FilesCouldBeMissed.getFilesInWebappPublicPluginDirectory(FilesCouldBeMissed.java:60)
> 	at com.jalios.ejpt.sync.strategy.FilesCouldBeMissed.run(FilesCouldBeMissed.java:44)
> 	at com.jalios.ejpt.sync.strategy.GlobalSyncStrategy.run(GlobalSyncStrategy.java:40)
> 	at com.jalios.ejpt.jobs.Util.previewSync(Util.java:37)
> 	at com.jalios.ejpt.jobs.SyncJob.run(SyncJob.java:31)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
> 

Plugin tree : 
![axeltiscoreplugin_et__log](https://cloud.githubusercontent.com/assets/5745780/23256327/42e4fc76-f9bf-11e6-9d21-3ec7b6fe5d8a.jpg)

This exception appears since I use Neon 2, and randomly (I think).

**Comment by OlivierJaquemet** [comment]
@KevinMoreau3 thanks for the feedback. unfortunately we do not have any active maintainer on this plugin (initially created by @lxtuong) . If you want to clone and contribute, we will be glad to merge a pull request !

**Comment by lxtuong** [comment]
@KevinMoreau3 as said Olivier, if you want to contribute and upgrade this plugin for Neon, just follow this guide : https://community.jalios.com/jcms/jc_98276/en/quickstart-ejpt-development-environment. Unfortunately, i'm on on others projects right now but I could give some help / hint sometimes.

**Comment by KevinMoreau3** [comment]
@lxtuong Thanks for the link. 
I will work on it when I've time.
